final List<Map<String, String>> jsonData = [
  {"name": "Abhishek", "level": "Basic"},
  {"name": "Tarun", "level": "Intermediate"},
  {"name": "Mohan", "level": "Advanced"},
  {"name": "Mohan", "level": "Intermediate"},
  {"name": "Raja", "level": "Basic"},
  {"name": "Neha", "level": "Advanced"},
  {"name": "Ravi", "level": "Basic"},
  {"name": "Kiran", "level": "Intermediate"},
  {"name": "Suman", "level": "Basic"},
  {"name": "Rahul", "level": "Intermediate"},
  {"name": "Preeti", "level": "Advanced"},
  {"name": "Sarita", "level": "Intermediate"},
  {"name": "Rakesh", "level": "Advanced"},
  {"name": "Suresh", "level": "Basic"},
  {"name": "Priya", "level": "Intermediate"},
  {"name": "Anjali", "level": "Basic"},
  {"name": "Rajiv", "level": "Advanced"},
  {"name": "Amit", "level": "Intermediate"},
  {"name": "Vikas", "level": "Basic"},
  {"name": "Nisha", "level": "Intermediate"},
  {"name": "Arun", "level": "Basic"},
];
